# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Pour < Formula
  desc "Install skills for any AI agent in one command"
  homepage "https://dev-kitx.github.io/pour-cli/"
  version "0.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/Dev-kitx/pour-cli/releases/download/v0.1.0/pour_0.1.0_darwin_amd64.tar.gz"
      sha256 "eca0a5e74ef4c86b6c21ed6a54741c3a8e1a3e3c3bcf6de25f5b828b2f20abe7"

      define_method(:install) do
        bin.install "pour"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/Dev-kitx/pour-cli/releases/download/v0.1.0/pour_0.1.0_darwin_arm64.tar.gz"
      sha256 "b34fdf1307ed0983787d9c79f949748201d239868934d20ccddeb86098d65903"

      define_method(:install) do
        bin.install "pour"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dev-kitx/pour-cli/releases/download/v0.1.0/pour_0.1.0_linux_amd64.tar.gz"
      sha256 "44bbef8a0b199e57080101f7c3aa95c627e5e121ba2cac8869462e9603a1e5bd"
      define_method(:install) do
        bin.install "pour"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/Dev-kitx/pour-cli/releases/download/v0.1.0/pour_0.1.0_linux_arm64.tar.gz"
      sha256 "1dca236a5e9a7a97b4f491d1c6c92fb971ff70ddde3d81f4073af84595d97fb2"
      define_method(:install) do
        bin.install "pour"
      end
    end
  end

  test do
    system "#{bin}/pour", "version"
  end
end
